services:
  # main:
  #   build: deploy/Dockerfile
  #   network_mode: host
  #   environment:
  #     - LLAMA_CLOUD_API_KEY=${LLAMA_CLOUD_API_KEY}
  #     - OPENAI_API_KEY=${OPENAI_API_KEY}
  #     - RAGAS_APP_TOKEN=${RAGAS_APP_TOKEN}
  #   depends_on:
  #     - weaviate
  #     - ollama
    
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.27.0
    ports:
    - 8080:8080
    - 50051:50051 
    volumes:
    - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_API_BASED_MODULES: 'true'
      CLUSTER_HOSTNAME: 'node1'
volumes:
  weaviate_data:
